theme: jekyll-theme-slate
title: [Dockerfile and Unix Commands]
description: [Implementar miniproyecto con dockerfile para la configuracion y automatizacion en el procesamiento de archivos csv]
show_downloads: true
